services:
  - type: web
    name: line-notion-bot
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_DB_ID
        sync: false
